# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_auto_20180721_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='评论者的姓名', max_length=100)),
                ('email', models.EmailField(help_text='评论者的邮箱', max_length=255)),
                ('url', models.URLField(blank=True, help_text='评论者的url地址')),
                ('text', models.TextField(help_text='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='评论添加的时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
