# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180723_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 4, 0, 54, 714332, tzinfo=utc), help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 4, 0, 54, 714370, tzinfo=utc), help_text='最后修改时间'),
        ),
    ]
