# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180723_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 6, 19, 51, 769701, tzinfo=utc), help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 6, 19, 51, 769740, tzinfo=utc), help_text='最后修改时间'),
        ),
    ]
