# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180723_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 5, 43, 22, 841592, tzinfo=utc), help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 5, 43, 22, 841630, tzinfo=utc), help_text='最后修改时间'),
        ),
    ]
