# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180726_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 11, 46, 14, 879032, tzinfo=utc), help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 11, 46, 14, 879071, tzinfo=utc), help_text='最后修改时间'),
        ),
    ]
