# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180803_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 12, 22, 19, 383210, tzinfo=utc), help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 12, 22, 19, 383248, tzinfo=utc), help_text='最后修改时间'),
        ),
    ]
